export {default as App} from './app/app'
export {default as Home} from './home/home'
export {default as Register} from './register/register'
export {default as Login} from './login/login'
export {default as Navbar} from './navbar/navbar'